name: Deploy to Azure Web App (Docker)

on:
  push:
    branches:
      - main # Runs when pushing to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: pallearning1995.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t pallearning1995.azurecr.io/mynodeazureapp:latest .
          docker push pallearning1995.azurecr.io/mynodeazureapp:latest

      # 🔥 Add Azure Login Step Before Deployment 🔥
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "pal-learning"
          images: "pallearning1995.azurecr.io/mynodeazureapp:latest"
